---
- name: Download OneAgent installer
  include_tasks: tasks/provide-installer/download.yml
  when: oneagent_local_installer|length == 0

- name: Transfer OneAgent installer
  include_tasks: tasks/provide-installer/transfer-{{ oneagent_system_family }}.yml
  when: oneagent_local_installer|length > 0

- name: Verify OneAgent installer signature
  include_tasks: tasks/provide-installer/signature-{{ oneagent_system_family }}.yml
  when: oneagent_system_is_unix
